version: '3.3'
services:
  motioneye:
    expose: 
      - "8765"
    ports: 
      - "8765:8765"      
    image: ccrisan/motioneye:master-armhf
    restart: unless-stopped
    environment:
      - hostname=motioneye
    container_name: motioneye
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
    
    
    